### ISSUE TITLE
现在一些安全软件的安全扫描结果，我们提供默认配置，不影响站点功能及使用。

### ISSUE THREAD

**Issue by terryzwt** [davyin-co/docker-nginx-php#14]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/terry/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<link rel=themeData
href="file:////Users/terry/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/terry/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=ZH-CN style='tab-interval:21.0pt;word-wrap:break-word;text-justify-trim:
punctuation'>

<div align=center>

序号 | 漏洞名称 | 漏洞等级 | 出现次数
-- | -- | -- | --
1 | 未设置X-Content-Type-Options响应头 | 低 | 1
2 | 未设置X-XSS-Protection响应头 | 低 | 1
3 | 点击劫持:无X-Frame-Options头信息 | 低 | 1
4 | 未设置Referrer-Policy响应头 | 低 | 1
5 | 未设置X-Download-Options响应头 | 低 | 1
6 | 未设置X-Permitted-Cross-Domain-Policies响应头 | 低 | 1
7 | 未设置Content-Security-Policy响应头 | 低 | 1

</div>

</body>

</html>

**Comment by lawxen** [comment]
查看 [drupal.conf ](https://github.com/davyin-co/docker-nginx-php/blob/main/conf/nginx/drupal.conf#L34)
只有下面三个配置未设置： 


序号 | 漏洞名称 | 漏洞等级 | 出现次数
-- | -- | -- | --
4 | 未设置Referrer-Policy响应头 | 低 | 1
5 | 未设置X-Download-Options响应头 | 低 | 1
6 | 未设置X-Permitted-Cross-Domain-Policies响应头 | 低 | 1

**Comment by lawxen** [comment]
```
add_header Referrer-Policy no-referrer;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
```

Referrer-Policy: no-referrer：这个响应头控制了浏览器如何在请求中发送 Referer 头。no-referrer 的值表示不发送 Referer 头。
X-Download-Options: noopen：这个响应头是为了防止 IE 在你的站点上打开下载的 HTML 文件。noopen 的值表示不允许直接打开下载的文件，而是强制下载保存。
X-Permitted-Cross-Domain-Policies: none：这个响应头用于防止 Adobe Flash 和 Adobe Acrobat 进行跨域请求。none 的值表示不允许任何跨域请求。
